# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aucC <- function(pos_predictor, neg_predictor) {
    .Call(`_aucC_aucC`, pos_predictor, neg_predictor)
}

