// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aucC
double aucC(NumericVector pos_predictor, NumericVector neg_predictor);
RcppExport SEXP _aucC_aucC(SEXP pos_predictorSEXP, SEXP neg_predictorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pos_predictor(pos_predictorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type neg_predictor(neg_predictorSEXP);
    rcpp_result_gen = Rcpp::wrap(aucC(pos_predictor, neg_predictor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aucC_aucC", (DL_FUNC) &_aucC_aucC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aucC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
